#!/usr/bin/env sh

set -ex

# install zoxide
sh ./install.d/zoxide

# install starship prompt https://starship.rs
sh ./install.d/starship --yes

# install stow, autosuggestions, fzf, and other dependencies
if command -v apt-get 2>&1 >/dev/null; then
  sudo apt-get update
  sudo apt-get install -y --no-install-recommends \
    fzf \
    stow \
    zoxide \
    zsh-autosuggestions \
    zsh-syntax-highlighting
elif command -v apk 2>&1 >/dev/null; then
  apk add --no-cache \
    fzf \
    stow \
    zoxide \
    zsh-autosuggestions \
    zsh-syntax-highlighting
else
  echo "distribution not supported"
  exit 1
fi

stow --version

# run stow to link everything
# this adopts existing files we would like to manage
# then resets them to what is in the repo.
stow --adopt -v --target="${HOME}" .
git restore .
